- hosts: tag_instance_filter_three_tier_app_werner* 
  gather_facts: false
  become: true
  tasks:
  - name: Check the instances status
    wait_for:
      host: "{{ item }}"
      port: 22
      search_regex: OpenSSH
      timeout: 600
#    delegate_to: localhost
    with_items:
      - "{{ inventory_hostname }}"
        
