- hosts: frontend
  gather_facts: false
  tasks:
  - name: OpenStack servers
    os_server_facts:
     cloud: ospcloud
     server: 'frontend'
    register: openstack_info
    tags:
      - osp.smoke
  - name: Use Uri module for wrting smoke test.
    uri:
     url: "http://{{item.public_v4}}"
     return_content: yes
    with_items:
      - "{{ openstack_info.ansible_facts.openstack_servers }}"
    register: webpage
    when: "'Ansible has done its job ' not in webpage.content"
    tags:
      - osp.smoke
