---
- name: Create Homework Assignment project Daniel Zecena
  # Student Werner Oroxon

  tower_project:
    name: "{{proj_name}}"
    description: "{{proj_description}}"
    organization: "{{org_name}}"
    state: present
    scm_type: git
    scm_url: https://github.com/dzecena79/ansible_advance_homework
    scm_update_on_launch: yes
    scm_branch: master
    #scm_credential: "/root/ansible_advance_homework/gitpass.yml"
    #scm_credential: git_key



- name: Machine Credential to connect to workstation using openstack.pub
  tower_credential:
    name: Connect_to_workstation
    organization: Default
    state: present
    kind: ssh
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
    tower_username: admin
    tower_password: r3dh4t1!
    ssh_key_data: "{{path_to_opentlc_key}}"
    username: cloud-user

- name: Create Inventory
  command: |
    tower-cli inventory create -n "{{static_inventory_name}}" --organization "{{org_name}}"
- name: Create Group in static inventory 
  command: |
    tower-cli group create --inventory "{{static_inventory_name}}"  --name {{group_name}}
- name: Add workstation host in tower_inventory 
  command: |
    tower-cli host create --inventory "{{static_inventory_name}}" --name "{{host_name}}"
- name: Associate workstation host to group 
  command: | 
    tower-cli host associate --host "{{host_name}}" --group "{{group_name}}"
- name: Tower Creds key file
  tower_credential:
    name: "{{ opentlc_cred_name }}"
    organization: Default
    state: present
    kind: ssh
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
    tower_username: admin
    tower_password: r3dh4t1!
    tower_verify_ssl: no
    become_method: "sudo"
    ssh_key_data: "{{ lookup('file', '/root/.ssh/mykey.pem') }}"
    username: "{{ opentlc_login }}"

- name: Remove secret
  file:
    name: /root/secret.pem
    state: absent
