---
# handlers file for app-tier

- name: restart-tomcat
  service:
   name: tomcat
   state: restarted
   enabled: yes

- name: start-apache
  service:
   name: httpd
   state: started
   enabled: yes
